# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 405c52b70ef1ca596e3b70c2a2f0673ffc4900a594b3ef2744d4414f4848ba9bd1b256383243ef830de35811d2b9c89af16805fd3f73eb2045f4ee3b171b4277

test:
  secret_key_base: 3faca45f33a3577826343b7416c51b78cbd6a411bb8232c3199687053e0262c579619e05dd630ee6d6d3190db0a77cd3091a2885ea92281ffd7e948aea502165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
